name: Release

on:
  push:
    tags: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  create_release:
    runs-on: ubuntu-20.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      git_tag: ${{ steps.get-git-tag.outputs.name }}
    steps:
      - name: Get Git tag
        id: get-git-tag
        run: |
          GIT_REF=${{ github.ref }}
          echo "::set-output name=name::${GIT_REF#refs/*/}"

      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-git-tag.outputs.name }}
          release_name: LOOT v${{ steps.get-git-tag.outputs.name }}
          draft: true
          body: |
            Requires a 64-bit version of Windows 10 (1809) or later and the [MSVC 2019 x64 redistributable](https://aka.ms/vs/16/release/vc_redist.x64.exe), and [7-Zip](https://www.7-zip.org/) to extract the archives. The list of changes can be found [here](https://loot.readthedocs.io/en/latest/app/changelog.html).

  windows:
    runs-on: windows-2019
    needs: create_release
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Get Boost metadata
        id: boost-metadata
        run: |
          echo "::set-output name=root::${{ github.workspace }}/boost_1_77_0"
          echo "::set-output name=librarydir::${{ github.workspace }}/boost_1_77_0/stage/64/lib"

      - name: Boost cache
        id: boost-cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.boost-metadata.outputs.root }}/boost
            ${{ steps.boost-metadata.outputs.root }}/stage
          key: ${{ runner.os }}-x64-Boost-1.77.0

      - name: Install JS dependencies
        run: npm ci

      - name: Download and extract svg_to_ico
        run: |
          curl -sfSLO 'https://github.com/Ortham/svg_to_ico/releases/download/1.1.0/svg_to_ico.7z'
          7z e -y svg_to_ico.7z

      - name: Generate ICO file
        run: .\svg_to_ico.exe -i resources\icons\loot.svg -o build\icon\icon.ico

      - name: Download & build Boost
        run: |
          curl -sSfLO https://raw.githubusercontent.com/Ortham/ci-scripts/2.1.2/install_boost.py
          python install_boost.py --directory ${{ github.workspace }} --boost-version 1.77.0 -a 64 locale system
        if: steps.boost-cache.outputs.cache-hit != 'true'

      - name: Download Qt
        id: qt-metadata
        run: |
          python -m pip install aqtinstall
          aqt install-qt windows desktop 6.2.1 win64_msvc2019_64
          echo "::set-output name=root::${{ github.workspace }}/6.2.1/msvc2019_64"

      - name: Run CMake
        run: |
          cd build
          cmake .. -G "Visual Studio 16 2019" -A x64 -DBOOST_ROOT="${{ steps.boost-metadata.outputs.root }}" -DBOOST_LIBRARYDIR="${{ steps.boost-metadata.outputs.librarydir }}" -DCMAKE_PREFIX_PATH="${{ steps.qt-metadata.outputs.root }}/lib/cmake"
          cmake --build . --config Release


      - name: Install packages for building docs
        run: |
          python -m pip install -r docs/requirements.txt

      - name: Build docs
        run: sphinx-build -b html docs build\docs\html

      - name: Build translation message object files
        run: node scripts\potomo.js

      - name: Build archive
        run: |
          $env:PATH="${{ steps.qt-metadata.outputs.root }}/bin;$env:PATH"
          node scripts\archive.js . ${{ needs.create_release.outputs.git_tag }}

      - name: Build installer
        run: scripts\build_installer.ps1 -LOOTIs64Bit

      - name: Get descriptive LOOT version
        id: get-loot-version
        shell: bash
        run: |
          GIT_DESCRIBE=$(git describe --tags --long --abbrev=7)
          GIT_REF=${{ github.ref }}
          LOOT_DESC_REF=${GIT_DESCRIBE}_${GIT_REF#refs/*/}
          LOOT_SAFE_DESC_REF=${LOOT_DESC_REF//[\/<>\"|]/_}
          echo "::set-output name=version::$LOOT_SAFE_DESC_REF"

      - name: Upload Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: build\loot_${{ steps.get-loot-version.outputs.version }}.7z
          asset_name: loot_${{ steps.get-loot-version.outputs.version }}.7z
          asset_content_type: application/x-7z-compressed

      - name: Upload Installer
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: build\LOOT Installer.exe
          asset_name: LOOT Installer.exe
          asset_content_type: application/octet-stream
